import { registerPage } from '../registry/page';
import '../sections';

registerPage('homepage', () => import('./homepage'));
registerPage('problem_main', () => import('./problem_main'));
registerPage('user_login', () => import('./user_login'), { layout: 'auth' });
registerPage('user_register', () => import('./user_register'), { layout: 'auth' });
registerPage('user_register_with_code', () => import('./user_register_with_code'), { layout: 'auth' });
registerPage('user_lostpass', () => import('./user_lostpass'), { layout: 'auth' });
registerPage('user_lostpass_with_code', () => import('./user_lostpass_with_code'), { layout: 'auth' });
registerPage('user_logout', () => import('./user_logout'), { layout: 'auth' });
registerPage('user_sudo', () => import('./user_sudo'), { layout: 'auth' });
registerPage('problem_create', () => import('./problem_create'));
registerPage('problem_edit', () => import('./problem_edit'));
registerPage('problem_import', () => import('./problem_import'));
registerPage('problem_detail', () => import('./problem_detail'));
registerPage('problem_submit', () => import('./problem_submit'));
registerPage('problem_hack', () => import('./problem_hack'));
registerPage('record_detail', () => import('./record_detail'));
registerPage('record_main', () => import('./record_main'));
registerPage('admin_ui', () => import('./admin_ui'));
